authorName: lscm
experimentName: elmo
trialConcurrency: 1

# Specify the maximum runing time, we specify 1 week here
maxExecDuration: 40h 
maxTrialNum: 9999
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
advisor:
  builtinAdvisorName: DFHB
  classArgs:
    random_seed: 0
    R: 4
    eta: 4
trial:
  command: python ./bin/train_elmo.py --train_prefix=./data/one_billion/1-billion-word-language-modeling-benchmark-r13output/training-monolingual.tokenized.shuffled/* --vocab_file ./data/vocab-2016-09-10.txt --save_dir ./output_model
  codeDir: .
  # specific the total number of GPU
  gpuNum: 2
